# Generated by Django 5.0 on 2024-08-04 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goods_id", models.IntegerField(null=True, verbose_name="물품 아이디")),
                ("goods_price", models.IntegerField(verbose_name="물품 가격")),
                ("goods_name", models.CharField(max_length=40, verbose_name="물품 이름")),
                ("goods_num", models.IntegerField(verbose_name="물품 재고")),
                ("item_url", models.CharField(max_length=40, verbose_name="물품 주소")),
                ("item_img", models.CharField(max_length=40, verbose_name="물품 이미지주소")),
            ],
        ),
        migrations.CreateModel(
            name="Basket_dream",
            fields=[
                ("basket_dream", models.AutoField(primary_key=True, serialize=False)),
                ("dbuy_num", models.IntegerField(default=0, verbose_name="구매갯수")),
                (
                    "dbuy_reason",
                    models.CharField(default="", max_length=300, verbose_name="구매 이유"),
                ),
                (
                    "dbasket_apply",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="꿈바구니 신청 날짜"
                    ),
                ),
                (
                    "dbasket_post",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="꿈바구니 등록 날짜"
                    ),
                ),
                (
                    "dstatus",
                    models.CharField(
                        default="승인대기", max_length=20, verbose_name="신청상태"
                    ),
                ),
                (
                    "dbasket_complete",
                    models.DateField(null=True, verbose_name="꿈바구니 완료 날짜"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Basket_heart",
            fields=[
                ("basket_heart", models.AutoField(primary_key=True, serialize=False)),
                ("hbuy_num", models.IntegerField(default=0, verbose_name="구매갯수")),
                (
                    "hbuy_reason",
                    models.CharField(default="", max_length=300, verbose_name="구매 이유"),
                ),
                (
                    "hbasket_apply",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="따숨바구니 신청 날짜"
                    ),
                ),
                (
                    "hstatus",
                    models.CharField(
                        default="승인대기", max_length=20, verbose_name="신청상태"
                    ),
                ),
                (
                    "hbasket_post",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="따숨바구니 등록 날짜"
                    ),
                ),
                (
                    "hbasket_complete",
                    models.DateField(null=True, verbose_name="따숨바구니 완료 날짜"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Basket_Item_dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goods_price", models.IntegerField(verbose_name="물품 가격")),
                ("goods_name", models.CharField(max_length=50, verbose_name="상품명")),
                ("item_url", models.CharField(max_length=300, verbose_name="상품 url")),
                ("buy_num", models.IntegerField(default=0, verbose_name="물품 수량")),
                ("total_price", models.IntegerField(default=0, verbose_name="총 가격")),
                ("complete", models.BooleanField(default=False)),
                (
                    "basket_dream",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.basket_dream",
                    ),
                ),
                (
                    "basket_heart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.basket_heart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benefit_name", models.CharField(max_length=30, verbose_name="수혜자이름")),
                ("address", models.CharField(max_length=30, verbose_name="수혜자 주소")),
                (
                    "address_det",
                    models.CharField(max_length=30, verbose_name="수혜자 세부주소"),
                ),
                (
                    "benefit_ssn",
                    models.CharField(max_length=30, verbose_name="수혜자 주민등록번호"),
                ),
                ("benefit_file", models.FileField(upload_to="uploads/")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="회원 아이디",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cheering",
            fields=[
                (
                    "cheering_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="응원메세지 고유번호"
                    ),
                ),
                (
                    "cheering_cont",
                    models.CharField(max_length=30, verbose_name="응원 문구"),
                ),
                (
                    "basket_dream",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.basket_dream",
                        verbose_name="꿈바구니 고유번호",
                    ),
                ),
                (
                    "basket_heart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.basket_heart",
                        verbose_name="따숨바구니 고유번호",
                    ),
                ),
                (
                    "user_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="회원 이메일",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CopyOfDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goods_total_price",
                    models.IntegerField(default=0, verbose_name="물품 총 가격"),
                ),
                (
                    "buy_date",
                    models.DateField(auto_now_add=True, null=True, verbose_name="구매일자"),
                ),
                ("payment", models.CharField(max_length=20, verbose_name="결제방법")),
                ("receipt_yn", models.BooleanField(default=True)),
                (
                    "basket_dream",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.basket_dream",
                    ),
                ),
                (
                    "basket_heart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.basket_heart",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donation_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.copyofdonation",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donation_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="물품 수량")),
                (
                    "basket_item_dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.basket_item_dream",
                    ),
                ),
                (
                    "donation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.copyofdonation",
                    ),
                ),
                (
                    "goods_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.goods",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("review_cont", models.CharField(max_length=300, verbose_name="후기 내용")),
                (
                    "review_img",
                    models.ImageField(upload_to="reviews/", verbose_name="후기 이미지"),
                ),
                (
                    "donation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.copyofdonation",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="회원 아이디",
                    ),
                ),
            ],
        ),
    ]
