# Generated by Django 5.0 on 2024-08-04 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="basket_dream",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="basket_heart",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="basket_item_dream",
            name="basket_dream",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donations.basket_dream",
            ),
        ),
        migrations.AddField(
            model_name="basket_item_dream",
            name="basket_heart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donations.basket_heart",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원 아이디",
            ),
        ),
        migrations.AddField(
            model_name="cheering",
            name="basket_dream",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donations.basket_dream",
                verbose_name="꿈바구니 고유번호",
            ),
        ),
        migrations.AddField(
            model_name="cheering",
            name="basket_heart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donations.basket_heart",
                verbose_name="따숨바구니 고유번호",
            ),
        ),
        migrations.AddField(
            model_name="cheering",
            name="user_email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원 이메일",
            ),
        ),
        migrations.AddField(
            model_name="copyofdonation",
            name="basket_dream",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donations.basket_dream",
            ),
        ),
        migrations.AddField(
            model_name="copyofdonation",
            name="basket_heart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donations.basket_heart",
            ),
        ),
        migrations.AddField(
            model_name="copyofdonation",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="donation_item",
            name="basket_item_dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="donations.basket_item_dream",
            ),
        ),
        migrations.AddField(
            model_name="donation_item",
            name="donation_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="donations.copyofdonation",
            ),
        ),
        migrations.AddField(
            model_name="donation_list",
            name="donation_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="donations.copyofdonation",
            ),
        ),
        migrations.AddField(
            model_name="donation_list",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="donation_item",
            name="goods_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="donations.goods"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="donation_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="donations.copyofdonation",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원 아이디",
            ),
        ),
    ]
