# Generated by Django 5.0 on 2024-08-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="item_img",
            field=models.CharField(max_length=40, verbose_name="물품 이미지주소"),
        ),
    ]
